apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: myjupyternotebook
  name: myjupyternotebook
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: myjupyternotebook
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: myjupyternotebook
    spec:
      containers:
        - image: amitatestregistry.azurecr.io/myjupyternotebook
          name: adminui
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
