apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: userui
  name: userui
spec:
  type: LoadBalancer
  ports:
    - name: "8889"
      port: 8889
      targetPort: 8080
  selector:
    io.kompose.service: userui
status:
  loadBalancer: {}