apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: userui
  name: userui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: userui
    spec:
      containers:
        - image: amitaghosh/inout_userui
          name: userui
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
